### ISSUE TITLE
InvalidArgumentError: Task 2 was not defined in job "worker"

### ISSUE THREAD

**Issue by AdamStelmaszczyk** [deepsense-ai/Distributed-BA3C#2]
I followed [these](https://github.com/deepsense-ai/Distributed-BA3C/pull/1) install steps. 

`a3c_virtualenv/bin/pip freeze` looks the same as `requirements.txt`.

I ran `python run_job.py -n 5 -g 60 -c 12 --use_sync --name neptune_job_name`, however there seem to be some errors, for example:

```
Traceback (most recent call last):
  File "/net/archive/groups/plggluna/adam/Distributed-BA3C/src/OpenAIGym//train.py", line 75, in <module>
    server = tf.train.Server(cluster_spec, job_name=my_job_name, task_index=my_task_index)
  File "/net/archive/groups/plggluna/adam/a3c_virtualenv/lib/python2.7/site-packages/tensorflow/python/training/server_lib.py", line 145, in __init__
    self._server_def.SerializeToString(), status)
  File "/net/software/local/python/2.7.9/lib/python2.7/contextlib.py", line 24, in __exit__
    self.gen.next()
  File "/net/archive/groups/plggluna/adam/a3c_virtualenv/lib/python2.7/site-packages/tensorflow/python/framework/errors_impl.py", line 466, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
InvalidArgumentError: Task 2 was not defined in job "worker"
```
Here is the full [log](https://gist.github.com/AdamStelmaszczyk/588176762829c8d4668b354ddfb2668d). Could you help me please?

**Comment by tgrel** [comment]
Looks like something's wrong with the cluster configuration passed to TensorFlow. Can you print the value of `cluster_spec` right before calling the the tf.train.Server constructor?

Additionally are you sure you're using the correct version of TensorFlow?

**Comment by AdamStelmaszczyk** [comment]
I added 
```
print('cluster_spec.as_dict(): {} tf.__version__: {}'.format(cluster_spec.as_dict(), tf.__version__))
```
before line 75, [the output](https://gist.github.com/AdamStelmaszczyk/20f2ac18e4621c437c1021719c27d368).

Yes, TF version is for sure 1.2.1:
```
cluster_spec.as_dict(): {'ps': ['p1567:9236'], 'worker': ['p1568:9237', 'p1577:9237']} tf.__version__: 1.2.1
```

**Comment by AdamStelmaszczyk** [comment]
Just a thought: maybe it's a race condition? `[worker:2] Starting the TF server` appears very late in the log, much earlier there is `InvalidArgumentError: Task 2 was not defined in job "worker"`.

**Comment by tgrel** [comment]
Something's not right, you're running a job with 5 nodes, but the cluster spec contains only 1 parameter server and 2 worker nodes. What about the missing 2 nodes? Maybe there's something wrong with the way the cluster spec is generated in your setup? Can you print the values of the environment variables in [here](https://github.com/deepsense-ai/Distributed-BA3C/blob/6d99428f2a930658c22bd630f4789ccffb4e9aa5/src/OpenAIGym/tensorflow_slurm_utils.py#L19) ?

I'd like to see what values do the SLURM environment variables have.

**Comment by tgrel** [comment]
I'm particularly interested in the `SLURM_JOB_NODELIST` variable

**Comment by AdamStelmaszczyk** [comment]
I printed this NODELIST along, `tf_server_from_slurm` returns correctly `cluster: {'ps': ['p1371:22814'], 'worker': ['p1372:22815', 'p1373:22815', 'p1374:22815', 'p1378:22815']}`.

However [here](https://github.com/deepsense-ai/Distributed-BA3C/blob/master/src/OpenAIGym/train.py#L68) there are only 2 workers. Because `args.eval_node` and `args.record_node` are surprisingly `True`.

**Comment by AdamStelmaszczyk** [comment]
[Here](https://github.com/deepsense-ai/Distributed-BA3C/blob/master/src/OpenAIGym/train.py#L55) in the `args` all the bool values are set to True:

`
Namespace(adam_debug=True, artificial_slowdown=0.0, batch_size=128, beta1=0.9, beta2=0.999, channels=3, conv_init='normal', cpu=1, cpu_device_count=None, debug_charts=True, do_train=1, dummy=0, dummy_predictor=0, early_stopping='None', env='Breakout-v0', epsilon=1e-08, eval_node=True, experiment_dir='/net/archive/groups/plggluna/adam/experiments/neptune_job_name_1517243793.51', fc_init='uniform', fc_neurons=256, fc_splits=1, frame_history=4, gamma=0.99, gpu=None, image_size=84, inter_op_par=None, intra_op_par=None, learning_rate=0.00015, load=None, local_time_max=5, max_epoch=1000, max_steps=None, mkl=0, mkl_num_threads=10, models_dir='/net/archive/groups/plggluna/adam/experiments/neptune_job_name_1517243793.51/models/', my_sim_master_queue=1, nr_predict_towers=3, nr_towers=1, num_grad=60, optimizer='adam', port=62048, predict_batch_size=16, ps=1, queue_size=1, record_node=True, replace_with_conv=True, save_every=0, schedule_hyper=True, send_debug_every=100, simulator_procs=100, steps_per_epoch=1000, sync=0, task='train', tf_port=15373, threads_to_trace=0, train_log_path='/net/archive/groups/plggluna/adam/experiments/neptune_job_name_1517243793.51/storage//atari_trainlog/', use_bias=0, use_sync_opt=1)
`

In `run_job.py` there is `parser` specification, but in `train.py` it's missing.

**Comment by AdamStelmaszczyk** [comment]
But now I don't understand how it could work for you :) We're both using Prometheus.

**Comment by AdamStelmaszczyk** [comment]
I see more now, it does `import parse` and `parse.parse_args()` which is defined [here](https://github.com/deepsense-ai/Distributed-BA3C/blob/master/src/OpenAIGym/parse.py)... So there is a specification... But `argparse` doesn't support `type=bool`, so this type is just ignored. So it treats the whole as a flag, so just passing `--eval_node anything` evaluates to True.

**Comment by AdamStelmaszczyk** [comment]
To reproduce your best results as it is written in README one needs to pass `--eval_node --record_node` so anyway `cluster['worker']` will have 2 nodes less because of these `cluster['worker'] = cluster['worker'][:-1]`... which leads to InvalidArgumentError...

**Comment by tgrel** [comment]
It might be a bug somewhere in the early stages of parameters parsing. Have you tried running it without specifying the --eval_node and --record_node flags? Have you tried running it with them set to True? I suspect that setting them directly to False can present invalid behavior (I don't recall us using these flags this way, so nobody tested it before you).

**Comment by AdamStelmaszczyk** [comment]
> Have you tried running it without specifying the --eval_node and --record_node flags? Have you tried running it with them set to True?

`distributed_tensorpack_mkl.sh` always passes `--eval_node $EVAL_NODE --record_node $RECORD_NODE` to `train.py`, so no matter what values $EVAL_NODE and $RECORD_NODE have, it will always evaluate to True, because `argparse` treats it as a switch and ignores the unsupported `type=bool`. So with the current code it's not possible to set them to False actually, they will be always True.

In `train.py`, after `args = parse.parse_args()` I added `args.eval_node = False` and `args.record_node = False` to force it - in that case there is no InvalidArgumentError.

> (I don't recall us using these flags this way, so nobody tested it before you)

In the [README](https://github.com/deepsense-ai/Distributed-BA3C#to-train-agent-on-atari-game) you  use them, the first command doesn't have `--eval_node --record_node`, the second one has. Anyway,  due to this `type=bool` bug, in `train.py` both `args.eval_node` and `args.record_node` are True, so you should have InvalidArgumentError. Maybe when you were running 68 or 71 workers you didn't notice 2 of them raising InvalidArgumentError, the training just continues with 2 workers less.

**Comment by tgrel** [comment]
I don't have means of testing this code at the moment. If you fix this issue on your side, I'd appreciate a Pull Request with the fix so that we can merge it to the master branch.

**Comment by AdamStelmaszczyk** [comment]
I was going to suggest that I can do a proper fix in PR (not using `type=bool` and passing or not passing `--evan_node` and other flags in `distributed_tensorpack_mkl.sh`, ok, will do that.

That `args.eval_node = False` and `args.record_node = False` was just a quick way to test if that was the problem.

**Comment by tgrel** [comment]
Thanks for fixing the issue. The PR is accepted and merged :) I'm closing the issue.
